### PR TITLE
Fixed issues when 'createCardToken' and 'createApplePayToken' request…

### PR DESCRIPTION
**Pull request by christianvershkov**
Fixed issues when 'createCardToken' and 'createApplePayToken' requests could return nothing if an unexpected error occurs.
Also, there is an ability now to expand NetworkError enum in order to handle more cases

### CODE REVIEW

**Comment by daven-gomes-cko** [comment]
Thanks for your contribution @christianvershkov 

Could you please keep the original method and add a new method with the new `NetworkError` type? Something like:

```
public func createCardToken(card: CkoCardTokenRequest,
                                successHandler: @escaping (CkoCardTokenResponse) -> Void,
                                errorHandler: @escaping (ErrorResponse) -> Void) {
// original implementation
}

public func createCardToken(card: CkoCardTokenRequest,
                                successHandler: @escaping (CkoCardTokenResponse) -> Void,
                                errorHandler: @escaping (NetworkError) -> Void) {
// same implementation as above, but using the new `NetworkError` type
}
```

This will mean there is no breaking change when we release this, and when we release a new major version of the SDK, we will remove the old method.

Also, there seems to be a [failing test](https://travis-ci.org/github/checkout/frames-ios/builds/725269149) on this PR:
```
Value of type 'NetworkError' has no member 'errorCodes'
	Testing cancelled because the build failed.
```

**Comment by daven-gomes-cko** [comment]
Perhaps you could even mark the old method as deprecated:
`@available(*, deprecated, message: "Use createCardToken with a NetworkError instead.")`

**Comment by daven-gomes-cko** [comment]
Hi @christianvershkov, may I ask if you are still working on this PR? 🙂

**Comment by christianvershkov** [comment]
@daven-gomes-cko  sorry for the late reply. Thank you for bringing it up. I will have finished it by tomorrow evening (I will do my best to have it done today)

**Comment by christianvershkov** [comment]
@daven-gomes-cko  I little bit updated my approach and added usage of Swift Result type (looks really better)

**Review by daven-gomes-cko — APPROVED** [review]

**Comment by daven-gomes-cko** [comment]
Thanks @christianvershkov for your contribution! We've merged this into `develop` and it will be included in the next release.

**Comment by christianvershkov** [comment]
Hi, @daven-gomes-cko 
Are there any updates on releasing this functionality?

**Comment by deepesh-vasthimal-cko** [comment]
Hi, @christianvershkov 
we are not planning to make a release this month. However the fix is merged into develop branch if you like to use it as a workaround. 
Thanks

**Pull request merged**
